### ISSUE TITLE
Operator namespace and cluster namespace parameters are not recognized in golang

### ISSUE THREAD

**Issue by travisn** [rook/kubectl-rook-ceph#101]
The `--operator-namespace` and `--namespace` flags are not recognized.

```
% bin/kubectl-rook-ceph -n foo health
Error: unknown command "-n" for "rook-ceph health"
```

```
% bin/kubectl-rook-ceph --operator-namespace foo health
Error: unknown command "--operator-namespace" for "rook-ceph health"
```

**Comment by subhamkrai** [comment]
@BlaineEXE these flags are not working as expected https://github.com/rook/kubectl-rook-ceph/blob/04e4ffa5a031b00c507a5616e6c5a3b8318746b4/cmd/commands/root.go#L52

I tried using `StringVarP` also but no luck

**Comment by travisn** [comment]
I wasn't able to repro this issue today. Building with the latest master of the krew plugin, I was able to run commands against other namespaces for both `--namespace` and `--operator-namespace`. Not sure what changed now. 

An improvement is that if the namespace doesn't exist, we should print an error message. Currently, it prints nothing if the namespace doesn't exist:
```
% bin/kubectl-rook-ceph --namespace=foo rook status
Info: 
```
