### ISSUE TITLE
--namespace does not work

### ISSUE THREAD

**Issue by lunderhage** [rook/kubectl-rook-ceph#129]
In v0.5.0, the --namespace argument is ignored and the plugin can not be used if the rook-ceph installation is not in the rook-ceph namespace.

**Comment by lunderhage** [comment]
I'm using Redhat's ODF so the rook operator and ceph cluster are in the openshift-storage namespace.

**Comment by subhamkrai** [comment]
> I'm using Redhat's ODF so the rook operator and ceph cluster are in the openshift-storage namespace.

@lunderhage okay, try this workaround and see if this works. until we have a fix
```kubectl rook-ceph --operator-namespace {namespace} ...```

**Comment by subhamkrai** [comment]
@lunderhage with 0.5.1 this issue should be fixed. Try and let us know.
