### ISSUE TITLE
[v0.5.0] oidc error

### ISSUE THREAD

**Issue by HaveFun83** [rook/kubectl-rook-ceph#134]
After plugin upgrade from 0.4.0 to 0.5.0 i got the following error when i want to use the kubectl rook-ceph plugin
```
Error: no Auth Provider found for name "oidc"
```
Maybe someone can help here?

**Comment by subhamkrai** [comment]
@HaveFun83 what command you were trying to run?

**Comment by HaveFun83** [comment]
I tried: `kubectl rook-ceph ceph status`
Cluster: On-Prem kubeadm v1.26.5

I manually rolled back to plugin v0.4.0 and everything is working again.

**Comment by HaveFun83** [comment]
We use keycloak as odic provider to authenticate our user (kubectl) against the kubernetes api.
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator

**Comment by HaveFun83** [comment]
@subhamkrai thank you so much. Works like a charm :rocket: :1st_place_medal:

**Comment by subhamkrai** [comment]
> @subhamkrai thank you so much. Works like a charm 🚀 🥇

Good to know it is working 🙂
