### ISSUE TITLE
--context flag no longer supported

### ISSUE THREAD

**Issue by taxilian** [rook/kubectl-rook-ceph#136]
The --context flag has been working in previous versions, but after the recent update (I think you changed to a golang version?) it no longer seems to be supported, which makes it a lot harder to use in my configuration

**Comment by subhamkrai** [comment]
@taxilian seems like we missed adding this flag, created the pr to add it back, apologies.

**Comment by taxilian** [comment]
I will of course hold a grudge for all of my days over the egregious oversight -- but it will probably be overshadowed by my appreciation of the tool, so I expect it'll even out in the end ;-) Let me know if I can help somehow.

**Comment by subhamkrai** [comment]
since pr is already there, so just wait for the release let me know if that works :XD

**Comment by subhamkrai** [comment]
@taxilian Test with the latest v0.5.2 version hopefully this should be fixed.
