### ISSUE TITLE
Redirect log messages to STDERR

### ISSUE THREAD

**Issue by lunderhage** [rook/kubectl-rook-ceph#139]
Some commands output json and the logs, eg 
```
Info: running 'ceph' command with args: [status]
```
show up in stdout, ruining json parsing of that output. Please redirect those to stderr.

**Comment by lunderhage** [comment]
Here is a fix: https://github.com/rook/kubectl-rook-ceph/pull/141

**Comment by subhamkrai** [comment]
@lunderhage could you explain more about the issue and in the pr about the changes you are bringing?

Thanks.

**Comment by lunderhage** [comment]
The PR redirects the log messages to stderr so that the json output from some commands can be parsed with eg jq.
