### ISSUE TITLE
Add more command to plugin

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#17]
Here are some commands we might consider:

- [x] `kubectl rook-ceph get-mon-endpoints`
- [ ] `kubectl rook-ceph set-mon-endpoints`: For disaster recovery, update the `rook-ceph-mon-endpoints` configmap and restart the operator
-  [ ] `kubectl rook-ceph force-mon-quorum <mon>`: Automate the disaster recovery guide for forcing the mon quorum to a single mon
- [ ] `kubectl rook-ceph get-volumes [rwx|rwo|cephfs|rbd]`
- [x] `kubectl rook-ceph ceph <args>`: Run any ceph command in the toolbox
- [x] `kubectl rook-ceph operator restart`: Restart the operator
- [x] `kubectl rook-ceph operator set <property> <value>`: Set the property in the `rook-ceph-operator-config` configmap, for example to enable debug logging or configure the CSI driver
- [x] `kubectl rook-ceph rook version`: Print the version of Rook and the version of Ceph daemons from the CephCluster CR status
- [x] `kubectl rook-ceph rook status`: Print the phase and/or conditions of every Ceph CR
- [ ] `kubectl rook-ceph rook purge-osd <id>`: Replace the purge-osd.yaml example job
- [ ] `kubectl rook-ceph set-pool-failure-domain <pool> <domain>`: Replace the advanced topic for updating a pool's failure domain

**Comment by BlaineEXE** [comment]
Travis' suggestion above does follow the kubectl trend for pods, etc.

For `get-volumes`, `rwx|rwo` and `cephfs|rbd` are not mutually exclusive. A user could want to list cephfs volumes that are only rwx or only rwo, for example.

IMO, `kubectl rook-ceph rook health` should show the rook health. If users want ceph status, they have a command for that.

How are `kubectl rook-ceph rook health` and `kubectl rook-ceph rook status` different? Why do we need both when they seem like they have a lot of overlap?

**Comment by leseb** [comment]
I'm not sure about `get` and `set` approaches, they don't always feel applicable, for instance how is the purge-osd, status, health are going to use it? I feel like this break the consistency and that just using `set-mon-endpoint` might be ok as one of the arguments.

**Comment by travisn** [comment]
After a bit more thought, having a single command does keep the implementation simpler. Splitting into multiple words such as `set mons` or `set pool failureDomain` doesn't add much. What about the following command guidelines?
- Commands are a single word (possibly hyphenated)
- Don't use the "get" prefix. Getting something can be implicit
- Prefer short commands as long as they are obvious enough

For example:
```
# get the mons
kubectl rook-ceph mons 
# set the mons 
kubectl rook-ceph set-mons
# just use the single word "set" instead of "operator set". If this is too generic, maybe "operator-set" would be better
kubectl rook-ceph set <property> <value>
# some commands will still be long
kubectl rook-ceph set-pool-failure-domain ...
```

**Comment by subhamkrai** [comment]
> Travis' suggestion above does follow the kubectl trend for pods, etc.
> 
> For `get-volumes`, `rwx|rwo` and `cephfs|rbd` are not mutually exclusive. A user could want to list cephfs volumes that are only rwx or only rwo, for example.
> 
> IMO, `kubectl rook-ceph rook health` should show the rook health. If users want ceph status, they have a command for that.
> 
> How are `kubectl rook-ceph rook health` and `kubectl rook-ceph rook status` different? Why do we need both when they seem like they have a lot of overlap?

right, and we already discussed that in [here](https://github.com/rook/kubectl-rook-ceph/pull/18#issuecomment-1024278291). I'll go ahead and remove this one.

**Comment by subhamkrai** [comment]
@leseb @travisn @BlaineEXE I have changed accordingly and split the changes per commit according to commands.

I'll create separate issues that are not covered in #18 PR.
