### ISSUE TITLE
Unable to restore-quorum on reef release

### ISSUE THREAD

**Issue by EggieCode** [rook/kubectl-rook-ceph#185]
When you run the restore-quorum it will fail with a error about public_bind_addr.

Error log:
```
Info: pod rook-ceph-mon-o-6d5c587b44-qs7f4 is ready for debugging
Info: fetching the deployment rook-ceph-mon-o-debug to be running

Info: deployment rook-ceph-mon-o-debug exists

Info: Started debug pod, restoring the mon quorum in the debug pod
Info: Extracting the monmap
parse error setting 'public_bind_addr' to ''

Error: command terminated with exit code 137
```

After removing https://github.com/rook/kubectl-rook-ceph/blob/master/pkg/mons/restore_quorum.go#L187 and recompile it works.

**Comment by travisn** [comment]
In a test cluster with v18 I was able to see this output:
```
parse error setting 'public_bind_addr' to ''
```

However, the restore still continued. Looks good to remove that parameter. Removing it worked for me as well. 
@EggieCode or @subhamkrai Want to open a PR for that?

**Comment by EggieCode** [comment]
Maybe a better idea is build a catch in for reef (v18) release.

**Comment by shay1760** [comment]
I would like to work on this issue.
