### ISSUE TITLE
Create kubectl plugin as additional tool for configuring and troubleshooting Rook

### ISSUE THREAD

**Issue by travisn** [rook/kubectl-rook-ceph#2]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Create a [Krew](https://krew.sigs.k8s.io/) plugin to extend `kubectl` commands for Rook.

**What is use case behind this feature:**
kubectl plugins provide additional conveniences for running kubectl commands. This can be a very helpful tool for troubleshooting or automating steps that today are manual or not obvious to collect. This is another tool that can help supplement our documentation around advanced configuration or disaster recovery, besides some common commands to simplify the life of Rook users.

Here are some commands we might consider:

- `kubectl rook get-mon-endpoints`
- `kubectl rook set-mon-endpoints`: For disaster recovery, update the `rook-ceph-mon-endpoints` configmap and restart the operator
- `kubectl rook force-mon-quorum <mon>`: Automate the disaster recovery guide for forcing the mon quorum to a single mon
- `kubectl rook get-volumes [rwx|rwo|cephfs|rbd]`
- `kubectl rook ceph <args>`: Run any ceph command in the toolbox
- `kubectl rook operator restart`: Restart the operator
- `kubectl rook operator set <property> <value>`: Set the property in the `rook-ceph-operator-config` configmap, for example to enable debug logging or configure the CSI driver
- `kubectl rook health`: Shortcut to “ceph status” command, or else pretty print the status on the CephCluster CR
- `kubectl rook version`: Print the version of Rook and the version of Ceph daemons from the CephCluster CR status
- `kubectl rook status`: Print the phase and/or conditions of every Ceph CR
- `kubectl rook purge-osd <id>`: Replace the purge-osd.yaml example job
- `kubectl rook set-pool-failure-domain <pool> <domain>`: Replace the advanced topic for updating a pool's failure domain

All commands would default to the `rook-ceph` namespace. For other namespaces pass `-n <namespace>`, or pick up the environment variable `ROOK_NAMESPACE`.

Likely we should create a new repo for this tool, no need to version it with the main Rook releases.

**Comment by sp98** [comment]
Projects usually try to follow below format for the commands: 

`<Top Level Command> <Command> <Resource> <Arguments> <Flags>`

For example:
`Kubectl get pods -n rook-ceph`

So 
`kubectl rook-ceph operator config get` could be something like:

`kubectl rook-ceph get operator-config`
