### ISSUE TITLE
is possible to support "ceph daemon cmd"?

### ISSUE THREAD

**Issue by zhucan** [rook/kubectl-rook-ceph#208]
such as: "ceph daemon osd.x dump_historic_ops"?

**Comment by travisn** [comment]
I could see a command like this:
```
kubectl rook-ceph daemon osd.x <args>
```

Where the plugin would exec into the daemon pod and exec the command. This is different from the `kubectl rook-ceph ceph <args>` command since it requires connecting to the daemon pod instead of the operator or toolbox pods.

**Comment by zhucan** [comment]
Don't support  "kubectl roo-ceph daemon osd.x <args>". @travisn

**Comment by travisn** [comment]
@zhucan What command do you want? This repo is for the kubectl plugin, so all commands need to start with `kubectl rook-ceph`.

**Comment by zhucan** [comment]
`kubectl rook-ceph daemon osd.x dump_historic_ops` @travisn

**Comment by travisn** [comment]
Sounds good, that is the same command I was suggesting, it would just be more flexible to allow other daemon commands as well.

**Comment by anthonyeleven** [comment]
I agree with Travis.  I need to collect heap stats and blocked op stats, for example, from OSD admin sockets.  

I _think_ `ceph daemon` has to be executed on the node where the desired daemon is running, so implementing this may require the plugin to, e.g., `ceph osd find 1701`, `ceph mon metadata`, etc.

**Comment by travisn** [comment]
> I agree with Travis. I need to collect heap stats and blocked op stats, for example, from OSD admin sockets.
> 
> I _think_ `ceph daemon` has to be executed on the node where the desired daemon is running, so implementing this may require the plugin to, e.g., `ceph osd find 1701`, `ceph mon metadata`, etc.

Rather than executing it on the node, I would expect the plugin connects to the running daemon pod to run against the local admin port.
