### ISSUE TITLE
Add command to purge osd 

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#21]
Add command for:

- [ ] `kubectl rook-ceph rook purge-osd <id>`: Replace the purge-osd.yaml example job

**Comment by subhamkrai** [comment]
@travisn since we have cr for this, do we want to add it to the tool?

**Comment by travisn** [comment]
The purge-osd job example basically just runs a command that could be run in the operator pod. So I think this would actually be a nice addition to the krew plugin.
