### ISSUE TITLE
Address the unchecked scenarios for stale subvolume command

### ISSUE THREAD

**Issue by yati1998** [rook/kubectl-rook-ceph#211]
In reference to the PR: https://github.com/rook/kubectl-rook-ceph/pull/206,
there are few comments which needs to be addressed and some unchecked scenarios:
1. Print the output in proper format
2. include the type(stale/bound) while listing the subvolumes
3. delete the omap values for the stale subvolumes
4. check for pending clones and external ceph cluster presence

Checkout the document for more details:
https://docs.google.com/document/d/1leSMY06IDkQD0weJ62mjgcJXAbppbNgR3u7nU-dSifo/edit

**Comment by yati1998** [comment]
Hey guys, adding a document for the steps that needs to be followed to connect to external cluster. https://docs.google.com/document/d/18fAS4zBgKAEnmESzm38AP2mVgY0AkCgjrlf2OFNoseQ/edit . In my opinion, rather than adding these steps to the script, we can rather add pre-requisites before running the subvolume command in external cluster. Let me know your thoughts on it. cc @travisn @Madhu-1

**Comment by subhamkrai** [comment]
@yati1998 what's the status on this?

**Comment by subhamkrai** [comment]
do we need to keep this issue open or closing this one and opening new issue for formatting sounds good

> yes, its done. Just a little formatting is required
