### ISSUE TITLE
No ability to specify namespace

### ISSUE THREAD

**Issue by DomantasGiedraitis** [rook/kubectl-rook-ceph#24]
Hey all,

I will start by saying this plugin is a great idea. Good work folks! 

**Issue**
I am unable to specify the namespace. It looks like it defaults to `rook-ceph` and `--namespace <custom-namespace>` doesn't override it.

**Reproduction Steps**
Run `kubectl rook-ceph ceph status --namespace my-custom-namespace`

**Expected Output**
The rook-ceph would check for OSDs in to `my-custom-namespace` namespace and return the value.

**Actual Output**
```
Error from server (NotFound): namespaces "rook-ceph" not found
```

**Comment by subhamkrai** [comment]
@DomantasGiedraitis thanks for opening the issue, I'll look into this

**Comment by subhamkrai** [comment]
@DomantasGiedraitis also, for custom namespace the syntax is 
```console
kubectl rook-ceph  --namespace my-custom-namespace ceph status
```

but in future, we'll remove this limitation.

**Comment by DomantasGiedraitis** [comment]
Nice one! Thanks for a quick response. I will give it a go 👍
