### ISSUE TITLE
Whither radosgw-admin?

### ISSUE THREAD

**Issue by anthonyeleven** [rook/kubectl-rook-ceph#253]
This plugin is good stuff.  I find however that many of the tasks I invoke a toolbox exec for are "radosgw" commands, which are currently not implemented.  So consider this an RFE.

I also often do "watch ceph -s".  I haven't tested, but I wonder what the latency of krew commands is like, if this would work well with the default 2 second interval, or if perhaps the plugin running the watch itself might work well.

**Comment by subhamkrai** [comment]
@anthonyeleven currently the tool doesn't support the watch command.

**Comment by anthonyeleven** [comment]
So? The point is that the tool does not support `radosgw-admin`

**Comment by subhamkrai** [comment]
> So? The point is that the tool does not support `radosgw-admin`

with my above `radosgw-admin` command will be supported, I was talking about `watch` is not supported with ceph commands

**Comment by anthonyeleven** [comment]
That was clear, but is not what I ask for here.  The Rook folks seem to prefer sending me to the KREW plugin vs enhancing their toolbox, but the lack of radosgw-admin support prevents me from using this.

**Comment by anthonyeleven** [comment]
Toolbox is rather more difficult to use with automation, and merging can't happen until someone plans and writes, which unless you know something I don't won't be anytime soon.

**Comment by travisn** [comment]
@anthonyeleven Any blockers for using the plugin besides radosgw-admin? I'm hoping https://github.com/rook/kubectl-rook-ceph/pull/296 will be merged and a release out in the next couple days.

**Comment by anthonyeleven** [comment]
The lack of RGW functionality has been a non-starter, if that gets merged and released, then I can look into the rest.
