### ISSUE TITLE
`rados` command should be available in the plugin

### ISSUE THREAD

**Issue by travisn** [rook/kubectl-rook-ceph#268]
The plugin should have commands for all ceph tools. Currently the plugin cannot execute `radosgw-admin` as described in [this rook issue](https://github.com/rook/rook/issues/13263#issuecomment-1912677820). Similarly, `rados` should also be exposed. Recently #237 implemented `rados` internally to run commands as part of other commands, but it isn't yet exposed for users to run it as a plugin command.

**Comment by travisn** [comment]
#253 is for radosgw-admin, just keeping this issue for `rados` commands

**Comment by OdedViner** [comment]
Can I get this issue?
