### ISSUE TITLE
Add support for the `--context` flag

### ISSUE THREAD

**Issue by taxilian** [rook/kubectl-rook-ceph#30]
I maintain four different kubernetes clusters which are all running rook; currently to use one or the other I have to switch the default context first, which is of course doable but is a bit annoying:

```
kubectl config use-context cluster1
kubectl rook-ceph ceph status
```

With all other kubectl commands I can use the `--context` flag, e.g.

```
kubectl get pods -o wide --context cluster1
```

It would be nice to be able to do that with this plugin as well.

BTW, thank you so much for making this plugin -- it's fantastic =]

**Comment by subhamkrai** [comment]
@taxilian thanks for the feedback. Will get this fixed. Also, would like to hear more feedback.

**Comment by taxilian** [comment]
It's been a fantastic tool for me -- my only frustration is that I normally have some bash aliases for which cluster I'm working with, e.g.:

```
alias kgc1='kubectl --context cluster1'
alias kgc2='kubectl --context cluster2'
alias kgc3='kubectl --context cluster3'
```

Then when I run things I just use `kgc1 -n prod get pods -o wide`, etc. I don't know if it's possible to support `--context` before the plugin or not, but if it is that would make this 10x more useful for me =]

I'm a relative newb to ceph, so learning as I go, but it is *so* much nicer to just use this rather than needing to create a toolbox pod.
