### ISSUE TITLE
`waitForPodToRun` does not account for multiple pods

### ISSUE THREAD

**Issue by Luminger** [rook/kubectl-rook-ceph#304]
When I ran `kubectl rook-ceph ceph status` on my cluster, the command never succeeded as it did not pick up on the currently running `ceph-operator` pod:

```
$ kubectl rook-ceph --operator-namespace=rook-ceph ceph status -h
Info: waiting for pod with label "app=rook-ceph-operator" in namespace "rook-ceph" to be running
Info: waiting for pod with label "app=rook-ceph-operator" in namespace "rook-ceph" to be running
[...]
```

But the `rook-ceph` operator was running fine:
```
$ kubectl get pods -n rook-ceph
[...]
rook-ceph-operator-695f48c6bd-r85m8                      0/1     Completed   0               7d19h
rook-ceph-operator-d7fcdf58b-6wnm5                       1/1     Running     0               20h
[...]
```

I noticed however that the previous operator pod `rook-ceph-operator-695f48c6bd-r85m8` was still around. This pod belonged to a previous `ReplicaSet` (I recently updated the cluster). Once deleted, the check was now satisfied and the plugin recognized the operator as being alive.

After checking the code, the root cause seems to be that `waitForPodToRun` does request the list of pods but it only ever checks the first pod returned in that list. The `Completed` pod apparently always came first back from the API, so the check never succeeded. Reworking this into iterating over all the returned pods should fix this. Another approach could be to filter for `Running` pods.

**Comment by subhamkrai** [comment]
thanks, @Luminger for looking into the code and tracking the issue. do you want to open the pr with a second approach to filter pod with `running` status?

**Comment by Luminger** [comment]
Sure, adding the filter shouldn't be too big of a deal 👍 I'll file a PR shortly.
