### ISSUE TITLE
Instead of random wait time in CI, read the resource details using Timeout

### ISSUE THREAD

**Issue by parth-gr** [rook/kubectl-rook-ceph#42]
```
+ kubectl rook_ceph -o test-operator -n test-cluster rbd ls replicapool
rbd: error opening pool 'replicapool': (2) No such file or directory
rbd: listing images failed: (2) No such file or directory
command terminated with exit code 2
Error: Process completed with exit code 2.
```

The CI failed because the wait time was not enough to reconcile the operator completely,

Instead of adding random wait time, we can read the resource until it becomes ready using Timeout,

LIke : https://github.com/rook/rook/blob/ec0c9a7963357fcd9023fc8d7c28720fe6f3c810/.github/workflows/canary-integration-test.yml#L59

**Comment by subhamkrai** [comment]
after this fix #38 I have not seen a CI issue, before this, I faced but not once was this merged.
try rebasing.

**Comment by parth-gr** [comment]
@subhamkrai You can see my PR is already on top of it https://github.com/rook/kubectl-rook-ceph/pull/36

Still, the CI fails with this error,

And anyhow using Timeout would be a good practice in time, when the CI would be growing more with commands:)

**Comment by subhamkrai** [comment]
right, checking for resource is better
Feel free to raise the pr
