### ISSUE TITLE
Flag position should not matter

### ISSUE THREAD

**Issue by parth-gr** [rook/kubectl-rook-ceph#44]
What if users want to issue the command like `kubectl rook-ceph start-debug <deploy> --image=my-image`? Or what if they do `kubectl rook-ceph start-debug --image my-image <deploy>`? This will fail in both cases. We should use the `parse_flags()` function for all flag parsing.

The commented-out `run_status_command()` example should help.

_Originally posted by @BlaineEXE in https://github.com/rook/kubectl-rook-ceph/pull/36#discussion_r935005719_

**Comment by BlaineEXE** [comment]
I think we have to be careful here. Flag positioning is really only a concern for commands that take an argument that is not a flag. At least for now, that case is limited to the last sub-command in a chain. I think it's sufficient to use `parse_flags()` twice to support this case without requiring further changes to `parse_flags()` which would complicate that function further.

**Comment by parth-gr** [comment]
@BlaineEXE do we also need to consider this case `kubectl rook-ceph  --image=my-image start-debug <deploy>`

**Comment by BlaineEXE** [comment]
I would say no. `--image` is a flag for `start-debug` and not a top-level flag. IIRC, kubectl has some "global" flags like `--namespace`, but many flags are only associated with a given subcommand and won't work before the subcommand.

**Comment by parth-gr** [comment]
Okay thanks
