### ISSUE TITLE
Split Krew side functionality into different files

### ISSUE THREAD

**Issue by parth-gr** [rook/kubectl-rook-ceph#64]
In krew we are seeing a lot of functionality added and in the future, it will be more,
So if we can split the functionality into different files keeping the base as `kubectl-rook-ceph.sh` would a good idea,
for `maintaining` `reviewing` and `implementing`, will become closer to object-oriented code:)

**Comment by travisn** [comment]
Krew allows for multiple files to be installed with a plugin?

**Comment by subhamkrai** [comment]
not valid anymore since we moved to golang.
