### ISSUE TITLE
Move the plugin from Bash to Golang

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#76]
In recent times we had lots of discussions regarding whether should we move the plugin to Golang or keep using bash. 

I'm opening this issue to get everyone's thoughts here and discuss the positive and negative sides of moving the plugin to Golang.

**Comment by subhamkrai** [comment]
Currently,  the positive side on moving to Golang I see are

1.  It will easily maintain with new releases and build
2. New contributors can contribute since not everyone like bash
3.  With bash, it will be difficult to manage the verrrry long scripts which with time it will keep on increasing and it will headache to maintain and will be error prone.

Negative sides on moving to Golang

1.  It will require big time for both the contributor and reviewer to get things going faster.
2. It will slow down the project
3.  Test the new build process

**Comment by subhamkrai** [comment]
@travisn @BlaineEXE @Madhu-1 @sp98 @parth-gr ^^

**Comment by Madhu-1** [comment]
Yes actually as @travisn mentioned, the downside is the transition from bash to golang, once it's done everything will be easy for maintenance and contribution.

**Comment by ideepika** [comment]
I like the idea of using bash helper/wrapper of sort for golang that @travisn  pointed out, we do a similar thing in teuthology(the testing framework for Ceph) and have python as the primary language.

**Comment by galexrt** [comment]
In regards to extensibility using existing Golang libraries such as [Cobra](https://github.com/spf13/cobra) and [Viper](https://github.com/spf13/viper) will make adding, e.g., more subcommands, easier as well.

**Comment by subhamkrai** [comment]
We finally moved to golang.
