### ISSUE TITLE
for dr health default debug mode should be `--debug-ms 0`

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#78]
currently, it has been noticed this with `dr health` command if no args are passed it prints log level of `--debug-ms 1`, we have not changed anything in the code but now somehow log level is `--debug-ms 1` by default noticed by @netzzer.

Anyway we should fix things by setting default log level to `--debug-ms 0`

**Comment by travisn** [comment]
Is that a ceph default or is the plugin changing that setting? Hopefully we can just use the ceph default.

**Comment by subhamkrai** [comment]
> Is that a ceph default or is the plugin changing that setting? Hopefully we can just use the ceph default.

looking at the code seems, we are using ceph default but I'll double-check when doing migration work

https://github.com/rook/kubectl-rook-ceph/blob/25b5248d568f5a62dd384af270b6840cb88abebc/kubectl-rook-ceph.sh#L787

**Comment by subhamkrai** [comment]
this is already fixed, will be present in next release with go migration.
