### ISSUE TITLE
Command to output status phase of all Rook-Ceph CRs

### ISSUE THREAD

**Issue by BlaineEXE** [rook/kubectl-rook-ceph#8]
Output the status phase of all Rook-Ceph CRs in a command.

E.g., `kubectl rook-ceph status`

It's probably good if this also outputs the ceph status as in `HEALTH_OK`, `HEALTH_WARN`, etc.

Example output:
```console
$> kubectl rook-ceph status
Namespace: rook-ceph
Operator: Running
CephCluster/my-cluster: Ready
  Ceph health: HEALTH_WARN
CephBlockPools
  my-pool    : Ready
  their-pool : Ready
CephObjectStores
  my-store   : Progressing
CephObjectStoreUsers
  my-user    : Progressing
CephFilesystems
  <none created>

**Comment by subhamkrai** [comment]
@BlaineEXE I already have similar command added here #18 in this commit https://github.com/rook/kubectl-rook-ceph/pull/18/commits/7bb9bc01de4766e5481a569a59f845b49ef08ce9 PTAL.
