### ISSUE TITLE
create first release of the tool

### ISSUE THREAD

**Issue by subhamkrai** [rook/kubectl-rook-ceph#9]
@travisn @leseb @BlaineEXE let's create 1st release of the tool if we are ready to go.  So, I that I can write a manifest file(sample manifest file https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/). After this manifest, we'll push this manifest to krew-index repo.

FYI, 
1. docs links to get an idea about deployment process
  https://krew.sigs.k8s.io/docs/developer-guide/

2. Step required to push manifest in krew-index
  https://krew.sigs.k8s.io/docs/developer-guide/release/new-plugin/

**Comment by BlaineEXE** [comment]
I think we can release now/soon as long as there is a way to release the tool with a version. We should probably start with 0.1 or better an `alpha` version so that users don't assume commands will be forward/backward compatible until we are ready to declare stable.

**Comment by BlaineEXE** [comment]
Semver says the below as well. I think we could also release as v0.y.z until we want to declare a stable API

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by travisn** [comment]
I created the [v0.0.1 release](https://github.com/rook/kubectl-rook-ceph/releases/tag/v0.0.1) to test the integration with krew. Next step is to open a krew PR with the manifest?

**Comment by subhamkrai** [comment]
> I created the [v0.0.1 release](https://github.com/rook/kubectl-rook-ceph/releases/tag/v0.0.1) to test the integration with krew. Next step is to open a krew PR with the manifest?

yes, after writing the manifest I'll test and then open PR on krew side with manifest. Thanks for the release

**Comment by subhamkrai** [comment]
Closing this as the first release has been created.
