### ISSUE TITLE
feature: replace-osd command

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/kubectl-rook-ceph#96]
We have already `purge-osd` command to remove OSDs. In addition, it's convenient to have `replace-osd` command to replace an OSD with a new OSD. Its main use case is replacing a broken OSD with a new one.

ref.
https://github.com/rook/rook/pull/12236

**Comment by travisn** [comment]
@satoru-takeuchi Can you provide more details for this issue? I'm not sure how this plugin can implement a `replace-osd` command. The plugin can purge/remove OSDs, but the creation of OSDs is owned by the OSD prepare job. I don't think we want to implement OSD creation in the plugin.

This is related to proposals in https://github.com/rook/rook/issues/11634 and https://github.com/rook/rook/issues/13240. Those changes will involve the OSD prepare pod.

**Comment by satoru-takeuchi** [comment]
@travisn This sub-command doesn't create osd dicrectly. Instead, it will purge an osd (like purge-osd subcommand) and restarts the operator pod to kick the new osd creation. It might be enough to create an option to restart the operator.

ref. https://github.com/rook/rook/pull/12236#issuecomment-1551068783

**Comment by travisn** [comment]
There is already an option for `kubectl rook-ceph operator restart`. So we can close this?
